/* Generated By:JavaCC: Do not edit this line. SqlParserImplConstants.java */
package com.github.pioneeryi.parser.impl;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SqlParserImplConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int A = 1;
  /** RegularExpression Id. */
  int ABS = 2;
  /** RegularExpression Id. */
  int ABSENT = 3;
  /** RegularExpression Id. */
  int ABSOLUTE = 4;
  /** RegularExpression Id. */
  int ACTION = 5;
  /** RegularExpression Id. */
  int ADA = 6;
  /** RegularExpression Id. */
  int ADD = 7;
  /** RegularExpression Id. */
  int ADMIN = 8;
  /** RegularExpression Id. */
  int AFTER = 9;
  /** RegularExpression Id. */
  int ALL = 10;
  /** RegularExpression Id. */
  int ALLOCATE = 11;
  /** RegularExpression Id. */
  int ALLOW = 12;
  /** RegularExpression Id. */
  int ALTER = 13;
  /** RegularExpression Id. */
  int ALWAYS = 14;
  /** RegularExpression Id. */
  int AND = 15;
  /** RegularExpression Id. */
  int ANY = 16;
  /** RegularExpression Id. */
  int APPLY = 17;
  /** RegularExpression Id. */
  int ARE = 18;
  /** RegularExpression Id. */
  int ARRAY = 19;
  /** RegularExpression Id. */
  int ARRAY_AGG = 20;
  /** RegularExpression Id. */
  int ARRAY_CONCAT_AGG = 21;
  /** RegularExpression Id. */
  int ARRAY_MAX_CARDINALITY = 22;
  /** RegularExpression Id. */
  int AS = 23;
  /** RegularExpression Id. */
  int ASC = 24;
  /** RegularExpression Id. */
  int ASENSITIVE = 25;
  /** RegularExpression Id. */
  int ASSERTION = 26;
  /** RegularExpression Id. */
  int ASSIGNMENT = 27;
  /** RegularExpression Id. */
  int ASYMMETRIC = 28;
  /** RegularExpression Id. */
  int AT = 29;
  /** RegularExpression Id. */
  int ATOMIC = 30;
  /** RegularExpression Id. */
  int ATTRIBUTE = 31;
  /** RegularExpression Id. */
  int ATTRIBUTES = 32;
  /** RegularExpression Id. */
  int AUTHORIZATION = 33;
  /** RegularExpression Id. */
  int AVG = 34;
  /** RegularExpression Id. */
  int BEFORE = 35;
  /** RegularExpression Id. */
  int BEGIN = 36;
  /** RegularExpression Id. */
  int BEGIN_FRAME = 37;
  /** RegularExpression Id. */
  int BEGIN_PARTITION = 38;
  /** RegularExpression Id. */
  int BERNOULLI = 39;
  /** RegularExpression Id. */
  int BETWEEN = 40;
  /** RegularExpression Id. */
  int BIGINT = 41;
  /** RegularExpression Id. */
  int BINARY = 42;
  /** RegularExpression Id. */
  int BIT = 43;
  /** RegularExpression Id. */
  int BLOB = 44;
  /** RegularExpression Id. */
  int BOOLEAN = 45;
  /** RegularExpression Id. */
  int BOTH = 46;
  /** RegularExpression Id. */
  int BREADTH = 47;
  /** RegularExpression Id. */
  int BY = 48;
  /** RegularExpression Id. */
  int C = 49;
  /** RegularExpression Id. */
  int CALL = 50;
  /** RegularExpression Id. */
  int CALLED = 51;
  /** RegularExpression Id. */
  int CARDINALITY = 52;
  /** RegularExpression Id. */
  int CASCADE = 53;
  /** RegularExpression Id. */
  int CASCADED = 54;
  /** RegularExpression Id. */
  int CASE = 55;
  /** RegularExpression Id. */
  int CAST = 56;
  /** RegularExpression Id. */
  int CATALOG = 57;
  /** RegularExpression Id. */
  int CATALOG_NAME = 58;
  /** RegularExpression Id. */
  int CEIL = 59;
  /** RegularExpression Id. */
  int CEILING = 60;
  /** RegularExpression Id. */
  int CENTURY = 61;
  /** RegularExpression Id. */
  int CHAIN = 62;
  /** RegularExpression Id. */
  int CHAR = 63;
  /** RegularExpression Id. */
  int CHAR_LENGTH = 64;
  /** RegularExpression Id. */
  int CHARACTER = 65;
  /** RegularExpression Id. */
  int CHARACTER_LENGTH = 66;
  /** RegularExpression Id. */
  int CHARACTER_SET_CATALOG = 67;
  /** RegularExpression Id. */
  int CHARACTER_SET_NAME = 68;
  /** RegularExpression Id. */
  int CHARACTER_SET_SCHEMA = 69;
  /** RegularExpression Id. */
  int CHARACTERISTICS = 70;
  /** RegularExpression Id. */
  int CHARACTERS = 71;
  /** RegularExpression Id. */
  int CHECK = 72;
  /** RegularExpression Id. */
  int CLASSIFIER = 73;
  /** RegularExpression Id. */
  int CLASS_ORIGIN = 74;
  /** RegularExpression Id. */
  int CLOB = 75;
  /** RegularExpression Id. */
  int CLOSE = 76;
  /** RegularExpression Id. */
  int COALESCE = 77;
  /** RegularExpression Id. */
  int COBOL = 78;
  /** RegularExpression Id. */
  int COLLATE = 79;
  /** RegularExpression Id. */
  int COLLATION = 80;
  /** RegularExpression Id. */
  int COLLATION_CATALOG = 81;
  /** RegularExpression Id. */
  int COLLATION_NAME = 82;
  /** RegularExpression Id. */
  int COLLATION_SCHEMA = 83;
  /** RegularExpression Id. */
  int COLLECT = 84;
  /** RegularExpression Id. */
  int COLUMN = 85;
  /** RegularExpression Id. */
  int COLUMN_NAME = 86;
  /** RegularExpression Id. */
  int COMMAND_FUNCTION = 87;
  /** RegularExpression Id. */
  int COMMAND_FUNCTION_CODE = 88;
  /** RegularExpression Id. */
  int COMMIT = 89;
  /** RegularExpression Id. */
  int COMMITTED = 90;
  /** RegularExpression Id. */
  int CONDITION = 91;
  /** RegularExpression Id. */
  int CONDITIONAL = 92;
  /** RegularExpression Id. */
  int CONDITION_NUMBER = 93;
  /** RegularExpression Id. */
  int CONNECT = 94;
  /** RegularExpression Id. */
  int CONNECTION = 95;
  /** RegularExpression Id. */
  int CONNECTION_NAME = 96;
  /** RegularExpression Id. */
  int CONSTRAINT = 97;
  /** RegularExpression Id. */
  int CONSTRAINT_CATALOG = 98;
  /** RegularExpression Id. */
  int CONSTRAINT_NAME = 99;
  /** RegularExpression Id. */
  int CONSTRAINT_SCHEMA = 100;
  /** RegularExpression Id. */
  int CONSTRAINTS = 101;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 102;
  /** RegularExpression Id. */
  int CONTAINS = 103;
  /** RegularExpression Id. */
  int CONTINUE = 104;
  /** RegularExpression Id. */
  int CONVERT = 105;
  /** RegularExpression Id. */
  int CORR = 106;
  /** RegularExpression Id. */
  int CORRESPONDING = 107;
  /** RegularExpression Id. */
  int COUNT = 108;
  /** RegularExpression Id. */
  int COVAR_POP = 109;
  /** RegularExpression Id. */
  int COVAR_SAMP = 110;
  /** RegularExpression Id. */
  int CREATE = 111;
  /** RegularExpression Id. */
  int CROSS = 112;
  /** RegularExpression Id. */
  int CUBE = 113;
  /** RegularExpression Id. */
  int CUME_DIST = 114;
  /** RegularExpression Id. */
  int CURRENT = 115;
  /** RegularExpression Id. */
  int CURRENT_CATALOG = 116;
  /** RegularExpression Id. */
  int CURRENT_DATE = 117;
  /** RegularExpression Id. */
  int CURRENT_DEFAULT_TRANSFORM_GROUP = 118;
  /** RegularExpression Id. */
  int CURRENT_PATH = 119;
  /** RegularExpression Id. */
  int CURRENT_ROLE = 120;
  /** RegularExpression Id. */
  int CURRENT_ROW = 121;
  /** RegularExpression Id. */
  int CURRENT_SCHEMA = 122;
  /** RegularExpression Id. */
  int CURRENT_TIME = 123;
  /** RegularExpression Id. */
  int CURRENT_TIMESTAMP = 124;
  /** RegularExpression Id. */
  int CURRENT_TRANSFORM_GROUP_FOR_TYPE = 125;
  /** RegularExpression Id. */
  int CURRENT_USER = 126;
  /** RegularExpression Id. */
  int CURSOR = 127;
  /** RegularExpression Id. */
  int CURSOR_NAME = 128;
  /** RegularExpression Id. */
  int CYCLE = 129;
  /** RegularExpression Id. */
  int DATA = 130;
  /** RegularExpression Id. */
  int DATABASE = 131;
  /** RegularExpression Id. */
  int DATE = 132;
  /** RegularExpression Id. */
  int DATETIME_INTERVAL_CODE = 133;
  /** RegularExpression Id. */
  int DATETIME_INTERVAL_PRECISION = 134;
  /** RegularExpression Id. */
  int DAY = 135;
  /** RegularExpression Id. */
  int DAYS = 136;
  /** RegularExpression Id. */
  int DEALLOCATE = 137;
  /** RegularExpression Id. */
  int DEC = 138;
  /** RegularExpression Id. */
  int DECADE = 139;
  /** RegularExpression Id. */
  int DECIMAL = 140;
  /** RegularExpression Id. */
  int DECLARE = 141;
  /** RegularExpression Id. */
  int DEFAULT_ = 142;
  /** RegularExpression Id. */
  int DEFAULTS = 143;
  /** RegularExpression Id. */
  int DEFERRABLE = 144;
  /** RegularExpression Id. */
  int DEFERRED = 145;
  /** RegularExpression Id. */
  int DEFINE = 146;
  /** RegularExpression Id. */
  int DEFINED = 147;
  /** RegularExpression Id. */
  int DEFINER = 148;
  /** RegularExpression Id. */
  int DEGREE = 149;
  /** RegularExpression Id. */
  int DELETE = 150;
  /** RegularExpression Id. */
  int DENSE_RANK = 151;
  /** RegularExpression Id. */
  int DEPTH = 152;
  /** RegularExpression Id. */
  int DEREF = 153;
  /** RegularExpression Id. */
  int DERIVED = 154;
  /** RegularExpression Id. */
  int DESC = 155;
  /** RegularExpression Id. */
  int DESCRIBE = 156;
  /** RegularExpression Id. */
  int DESCRIPTION = 157;
  /** RegularExpression Id. */
  int DESCRIPTOR = 158;
  /** RegularExpression Id. */
  int DETERMINISTIC = 159;
  /** RegularExpression Id. */
  int DIAGNOSTICS = 160;
  /** RegularExpression Id. */
  int DISALLOW = 161;
  /** RegularExpression Id. */
  int DISCONNECT = 162;
  /** RegularExpression Id. */
  int DISPATCH = 163;
  /** RegularExpression Id. */
  int DISTINCT = 164;
  /** RegularExpression Id. */
  int DOMAIN = 165;
  /** RegularExpression Id. */
  int DOT_FORMAT = 166;
  /** RegularExpression Id. */
  int DOUBLE = 167;
  /** RegularExpression Id. */
  int DOW = 168;
  /** RegularExpression Id. */
  int DOY = 169;
  /** RegularExpression Id. */
  int DROP = 170;
  /** RegularExpression Id. */
  int DYNAMIC = 171;
  /** RegularExpression Id. */
  int DYNAMIC_FUNCTION = 172;
  /** RegularExpression Id. */
  int DYNAMIC_FUNCTION_CODE = 173;
  /** RegularExpression Id. */
  int EACH = 174;
  /** RegularExpression Id. */
  int ELEMENT = 175;
  /** RegularExpression Id. */
  int ELSE = 176;
  /** RegularExpression Id. */
  int EMPTY = 177;
  /** RegularExpression Id. */
  int ENCODING = 178;
  /** RegularExpression Id. */
  int END = 179;
  /** RegularExpression Id. */
  int END_EXEC = 180;
  /** RegularExpression Id. */
  int END_FRAME = 181;
  /** RegularExpression Id. */
  int END_PARTITION = 182;
  /** RegularExpression Id. */
  int EPOCH = 183;
  /** RegularExpression Id. */
  int EQUALS = 184;
  /** RegularExpression Id. */
  int ERROR = 185;
  /** RegularExpression Id. */
  int ESCAPE = 186;
  /** RegularExpression Id. */
  int EVERY = 187;
  /** RegularExpression Id. */
  int EXCEPT = 188;
  /** RegularExpression Id. */
  int EXCEPTION = 189;
  /** RegularExpression Id. */
  int EXCLUDE = 190;
  /** RegularExpression Id. */
  int EXCLUDING = 191;
  /** RegularExpression Id. */
  int EXEC = 192;
  /** RegularExpression Id. */
  int EXECUTE = 193;
  /** RegularExpression Id. */
  int EXISTS = 194;
  /** RegularExpression Id. */
  int EXP = 195;
  /** RegularExpression Id. */
  int EXPLAIN = 196;
  /** RegularExpression Id. */
  int EXTEND = 197;
  /** RegularExpression Id. */
  int EXTERNAL = 198;
  /** RegularExpression Id. */
  int EXTRACT = 199;
  /** RegularExpression Id. */
  int FALSE = 200;
  /** RegularExpression Id. */
  int FETCH = 201;
  /** RegularExpression Id. */
  int FILTER = 202;
  /** RegularExpression Id. */
  int FINAL = 203;
  /** RegularExpression Id. */
  int FIRST = 204;
  /** RegularExpression Id. */
  int FIRST_VALUE = 205;
  /** RegularExpression Id. */
  int FLOAT = 206;
  /** RegularExpression Id. */
  int FLOOR = 207;
  /** RegularExpression Id. */
  int FOLLOWING = 208;
  /** RegularExpression Id. */
  int FOR = 209;
  /** RegularExpression Id. */
  int FORMAT = 210;
  /** RegularExpression Id. */
  int FOREIGN = 211;
  /** RegularExpression Id. */
  int FORTRAN = 212;
  /** RegularExpression Id. */
  int FOUND = 213;
  /** RegularExpression Id. */
  int FRAC_SECOND = 214;
  /** RegularExpression Id. */
  int FRAME_ROW = 215;
  /** RegularExpression Id. */
  int FREE = 216;
  /** RegularExpression Id. */
  int FROM = 217;
  /** RegularExpression Id. */
  int FULL = 218;
  /** RegularExpression Id. */
  int FUNCTION = 219;
  /** RegularExpression Id. */
  int FUSION = 220;
  /** RegularExpression Id. */
  int G = 221;
  /** RegularExpression Id. */
  int GENERAL = 222;
  /** RegularExpression Id. */
  int GENERATED = 223;
  /** RegularExpression Id. */
  int GEOMETRY = 224;
  /** RegularExpression Id. */
  int GET = 225;
  /** RegularExpression Id. */
  int GLOBAL = 226;
  /** RegularExpression Id. */
  int GO = 227;
  /** RegularExpression Id. */
  int GOTO = 228;
  /** RegularExpression Id. */
  int GRANT = 229;
  /** RegularExpression Id. */
  int GRANTED = 230;
  /** RegularExpression Id. */
  int GROUP = 231;
  /** RegularExpression Id. */
  int GROUP_CONCAT = 232;
  /** RegularExpression Id. */
  int GROUPING = 233;
  /** RegularExpression Id. */
  int GROUPS = 234;
  /** RegularExpression Id. */
  int HAVING = 235;
  /** RegularExpression Id. */
  int HIERARCHY = 236;
  /** RegularExpression Id. */
  int HOLD = 237;
  /** RegularExpression Id. */
  int HOP = 238;
  /** RegularExpression Id. */
  int HOUR = 239;
  /** RegularExpression Id. */
  int HOURS = 240;
  /** RegularExpression Id. */
  int IDENTITY = 241;
  /** RegularExpression Id. */
  int IGNORE = 242;
  /** RegularExpression Id. */
  int ILIKE = 243;
  /** RegularExpression Id. */
  int IMMEDIATE = 244;
  /** RegularExpression Id. */
  int IMMEDIATELY = 245;
  /** RegularExpression Id. */
  int IMPLEMENTATION = 246;
  /** RegularExpression Id. */
  int IMPORT = 247;
  /** RegularExpression Id. */
  int IN = 248;
  /** RegularExpression Id. */
  int INCLUDE = 249;
  /** RegularExpression Id. */
  int INCLUDING = 250;
  /** RegularExpression Id. */
  int INCREMENT = 251;
  /** RegularExpression Id. */
  int INDICATOR = 252;
  /** RegularExpression Id. */
  int INITIAL = 253;
  /** RegularExpression Id. */
  int INITIALLY = 254;
  /** RegularExpression Id. */
  int INNER = 255;
  /** RegularExpression Id. */
  int INOUT = 256;
  /** RegularExpression Id. */
  int INPUT = 257;
  /** RegularExpression Id. */
  int INSENSITIVE = 258;
  /** RegularExpression Id. */
  int INSERT = 259;
  /** RegularExpression Id. */
  int INSTANCE = 260;
  /** RegularExpression Id. */
  int INSTANTIABLE = 261;
  /** RegularExpression Id. */
  int INT = 262;
  /** RegularExpression Id. */
  int INTEGER = 263;
  /** RegularExpression Id. */
  int INTERSECT = 264;
  /** RegularExpression Id. */
  int INTERSECTION = 265;
  /** RegularExpression Id. */
  int INTERVAL = 266;
  /** RegularExpression Id. */
  int INTO = 267;
  /** RegularExpression Id. */
  int INVOKER = 268;
  /** RegularExpression Id. */
  int IS = 269;
  /** RegularExpression Id. */
  int ISODOW = 270;
  /** RegularExpression Id. */
  int ISOYEAR = 271;
  /** RegularExpression Id. */
  int ISOLATION = 272;
  /** RegularExpression Id. */
  int JAVA = 273;
  /** RegularExpression Id. */
  int JOIN = 274;
  /** RegularExpression Id. */
  int JSON = 275;
  /** RegularExpression Id. */
  int JSON_ARRAY = 276;
  /** RegularExpression Id. */
  int JSON_ARRAYAGG = 277;
  /** RegularExpression Id. */
  int JSON_EXISTS = 278;
  /** RegularExpression Id. */
  int JSON_OBJECT = 279;
  /** RegularExpression Id. */
  int JSON_OBJECTAGG = 280;
  /** RegularExpression Id. */
  int JSON_QUERY = 281;
  /** RegularExpression Id. */
  int JSON_VALUE = 282;
  /** RegularExpression Id. */
  int K = 283;
  /** RegularExpression Id. */
  int KEY = 284;
  /** RegularExpression Id. */
  int KEY_MEMBER = 285;
  /** RegularExpression Id. */
  int KEY_TYPE = 286;
  /** RegularExpression Id. */
  int LABEL = 287;
  /** RegularExpression Id. */
  int LAG = 288;
  /** RegularExpression Id. */
  int LANGUAGE = 289;
  /** RegularExpression Id. */
  int LARGE = 290;
  /** RegularExpression Id. */
  int LAST = 291;
  /** RegularExpression Id. */
  int LAST_VALUE = 292;
  /** RegularExpression Id. */
  int LATERAL = 293;
  /** RegularExpression Id. */
  int LEAD = 294;
  /** RegularExpression Id. */
  int LEADING = 295;
  /** RegularExpression Id. */
  int LEFT = 296;
  /** RegularExpression Id. */
  int LENGTH = 297;
  /** RegularExpression Id. */
  int LEVEL = 298;
  /** RegularExpression Id. */
  int LIBRARY = 299;
  /** RegularExpression Id. */
  int LIKE = 300;
  /** RegularExpression Id. */
  int LIKE_REGEX = 301;
  /** RegularExpression Id. */
  int LIMIT = 302;
  /** RegularExpression Id. */
  int LN = 303;
  /** RegularExpression Id. */
  int LOCAL = 304;
  /** RegularExpression Id. */
  int LOCALTIME = 305;
  /** RegularExpression Id. */
  int LOCALTIMESTAMP = 306;
  /** RegularExpression Id. */
  int LOCATOR = 307;
  /** RegularExpression Id. */
  int LOWER = 308;
  /** RegularExpression Id. */
  int M = 309;
  /** RegularExpression Id. */
  int MAP = 310;
  /** RegularExpression Id. */
  int MATCH = 311;
  /** RegularExpression Id. */
  int MATCHED = 312;
  /** RegularExpression Id. */
  int MATCHES = 313;
  /** RegularExpression Id. */
  int MATCH_NUMBER = 314;
  /** RegularExpression Id. */
  int MATCH_RECOGNIZE = 315;
  /** RegularExpression Id. */
  int MAX = 316;
  /** RegularExpression Id. */
  int MAXVALUE = 317;
  /** RegularExpression Id. */
  int MEASURES = 318;
  /** RegularExpression Id. */
  int MEMBER = 319;
  /** RegularExpression Id. */
  int MERGE = 320;
  /** RegularExpression Id. */
  int MESSAGE_LENGTH = 321;
  /** RegularExpression Id. */
  int MESSAGE_OCTET_LENGTH = 322;
  /** RegularExpression Id. */
  int MESSAGE_TEXT = 323;
  /** RegularExpression Id. */
  int METHOD = 324;
  /** RegularExpression Id. */
  int MICROSECOND = 325;
  /** RegularExpression Id. */
  int MILLISECOND = 326;
  /** RegularExpression Id. */
  int MILLENNIUM = 327;
  /** RegularExpression Id. */
  int MIN = 328;
  /** RegularExpression Id. */
  int MINUTE = 329;
  /** RegularExpression Id. */
  int MINUTES = 330;
  /** RegularExpression Id. */
  int MINVALUE = 331;
  /** RegularExpression Id. */
  int MOD = 332;
  /** RegularExpression Id. */
  int MODIFIES = 333;
  /** RegularExpression Id. */
  int MODULE = 334;
  /** RegularExpression Id. */
  int MONTH = 335;
  /** RegularExpression Id. */
  int MONTHS = 336;
  /** RegularExpression Id. */
  int MORE_ = 337;
  /** RegularExpression Id. */
  int MULTISET = 338;
  /** RegularExpression Id. */
  int MUMPS = 339;
  /** RegularExpression Id. */
  int NAME = 340;
  /** RegularExpression Id. */
  int NAMES = 341;
  /** RegularExpression Id. */
  int NANOSECOND = 342;
  /** RegularExpression Id. */
  int NATIONAL = 343;
  /** RegularExpression Id. */
  int NATURAL = 344;
  /** RegularExpression Id. */
  int NCHAR = 345;
  /** RegularExpression Id. */
  int NCLOB = 346;
  /** RegularExpression Id. */
  int NESTING = 347;
  /** RegularExpression Id. */
  int NEW = 348;
  /** RegularExpression Id. */
  int NEXT = 349;
  /** RegularExpression Id. */
  int NO = 350;
  /** RegularExpression Id. */
  int NONE = 351;
  /** RegularExpression Id. */
  int NORMALIZE = 352;
  /** RegularExpression Id. */
  int NORMALIZED = 353;
  /** RegularExpression Id. */
  int NOT = 354;
  /** RegularExpression Id. */
  int NTH_VALUE = 355;
  /** RegularExpression Id. */
  int NTILE = 356;
  /** RegularExpression Id. */
  int NULL = 357;
  /** RegularExpression Id. */
  int NULLABLE = 358;
  /** RegularExpression Id. */
  int NULLIF = 359;
  /** RegularExpression Id. */
  int NULLS = 360;
  /** RegularExpression Id. */
  int NUMBER = 361;
  /** RegularExpression Id. */
  int NUMERIC = 362;
  /** RegularExpression Id. */
  int OBJECT = 363;
  /** RegularExpression Id. */
  int OCCURRENCES_REGEX = 364;
  /** RegularExpression Id. */
  int OCTET_LENGTH = 365;
  /** RegularExpression Id. */
  int OCTETS = 366;
  /** RegularExpression Id. */
  int OF = 367;
  /** RegularExpression Id. */
  int OFFSET = 368;
  /** RegularExpression Id. */
  int OLD = 369;
  /** RegularExpression Id. */
  int OMIT = 370;
  /** RegularExpression Id. */
  int ON = 371;
  /** RegularExpression Id. */
  int ONE = 372;
  /** RegularExpression Id. */
  int ONLY = 373;
  /** RegularExpression Id. */
  int OPEN = 374;
  /** RegularExpression Id. */
  int OPTION = 375;
  /** RegularExpression Id. */
  int OPTIONS = 376;
  /** RegularExpression Id. */
  int OR = 377;
  /** RegularExpression Id. */
  int ORDER = 378;
  /** RegularExpression Id. */
  int ORDERING = 379;
  /** RegularExpression Id. */
  int ORDINALITY = 380;
  /** RegularExpression Id. */
  int OTHERS = 381;
  /** RegularExpression Id. */
  int OUT = 382;
  /** RegularExpression Id. */
  int OUTER = 383;
  /** RegularExpression Id. */
  int OUTPUT = 384;
  /** RegularExpression Id. */
  int OVER = 385;
  /** RegularExpression Id. */
  int OVERLAPS = 386;
  /** RegularExpression Id. */
  int OVERLAY = 387;
  /** RegularExpression Id. */
  int OVERRIDING = 388;
  /** RegularExpression Id. */
  int PAD = 389;
  /** RegularExpression Id. */
  int PARAMETER = 390;
  /** RegularExpression Id. */
  int PARAMETER_MODE = 391;
  /** RegularExpression Id. */
  int PARAMETER_NAME = 392;
  /** RegularExpression Id. */
  int PARAMETER_ORDINAL_POSITION = 393;
  /** RegularExpression Id. */
  int PARAMETER_SPECIFIC_CATALOG = 394;
  /** RegularExpression Id. */
  int PARAMETER_SPECIFIC_NAME = 395;
  /** RegularExpression Id. */
  int PARAMETER_SPECIFIC_SCHEMA = 396;
  /** RegularExpression Id. */
  int PARTIAL = 397;
  /** RegularExpression Id. */
  int PARTITION = 398;
  /** RegularExpression Id. */
  int PASCAL = 399;
  /** RegularExpression Id. */
  int PASSING = 400;
  /** RegularExpression Id. */
  int PASSTHROUGH = 401;
  /** RegularExpression Id. */
  int PAST = 402;
  /** RegularExpression Id. */
  int PATH = 403;
  /** RegularExpression Id. */
  int PATTERN = 404;
  /** RegularExpression Id. */
  int PER = 405;
  /** RegularExpression Id. */
  int PERCENT = 406;
  /** RegularExpression Id. */
  int PERCENTILE_CONT = 407;
  /** RegularExpression Id. */
  int PERCENTILE_DISC = 408;
  /** RegularExpression Id. */
  int PERCENT_RANK = 409;
  /** RegularExpression Id. */
  int PERIOD = 410;
  /** RegularExpression Id. */
  int PERMUTE = 411;
  /** RegularExpression Id. */
  int PIVOT = 412;
  /** RegularExpression Id. */
  int PLACING = 413;
  /** RegularExpression Id. */
  int PLAN = 414;
  /** RegularExpression Id. */
  int PLI = 415;
  /** RegularExpression Id. */
  int PORTION = 416;
  /** RegularExpression Id. */
  int POSITION = 417;
  /** RegularExpression Id. */
  int POSITION_REGEX = 418;
  /** RegularExpression Id. */
  int POWER = 419;
  /** RegularExpression Id. */
  int PRECEDES = 420;
  /** RegularExpression Id. */
  int PRECEDING = 421;
  /** RegularExpression Id. */
  int PRECISION = 422;
  /** RegularExpression Id. */
  int PREPARE = 423;
  /** RegularExpression Id. */
  int PRESERVE = 424;
  /** RegularExpression Id. */
  int PREV = 425;
  /** RegularExpression Id. */
  int PRIMARY = 426;
  /** RegularExpression Id. */
  int PRIOR = 427;
  /** RegularExpression Id. */
  int PRIVILEGES = 428;
  /** RegularExpression Id. */
  int PROCEDURE = 429;
  /** RegularExpression Id. */
  int PUBLIC = 430;
  /** RegularExpression Id. */
  int QUARTER = 431;
  /** RegularExpression Id. */
  int RANGE = 432;
  /** RegularExpression Id. */
  int RANK = 433;
  /** RegularExpression Id. */
  int READ = 434;
  /** RegularExpression Id. */
  int READS = 435;
  /** RegularExpression Id. */
  int REAL = 436;
  /** RegularExpression Id. */
  int RECURSIVE = 437;
  /** RegularExpression Id. */
  int REF = 438;
  /** RegularExpression Id. */
  int REFERENCES = 439;
  /** RegularExpression Id. */
  int REFERENCING = 440;
  /** RegularExpression Id. */
  int REGR_AVGX = 441;
  /** RegularExpression Id. */
  int REGR_AVGY = 442;
  /** RegularExpression Id. */
  int REGR_COUNT = 443;
  /** RegularExpression Id. */
  int REGR_INTERCEPT = 444;
  /** RegularExpression Id. */
  int REGR_R2 = 445;
  /** RegularExpression Id. */
  int REGR_SLOPE = 446;
  /** RegularExpression Id. */
  int REGR_SXX = 447;
  /** RegularExpression Id. */
  int REGR_SXY = 448;
  /** RegularExpression Id. */
  int REGR_SYY = 449;
  /** RegularExpression Id. */
  int RELATIVE = 450;
  /** RegularExpression Id. */
  int RELEASE = 451;
  /** RegularExpression Id. */
  int REPEATABLE = 452;
  /** RegularExpression Id. */
  int REPLACE = 453;
  /** RegularExpression Id. */
  int RESET = 454;
  /** RegularExpression Id. */
  int RESPECT = 455;
  /** RegularExpression Id. */
  int RESTART = 456;
  /** RegularExpression Id. */
  int RESTRICT = 457;
  /** RegularExpression Id. */
  int RESULT = 458;
  /** RegularExpression Id. */
  int RETURN = 459;
  /** RegularExpression Id. */
  int RETURNED_CARDINALITY = 460;
  /** RegularExpression Id. */
  int RETURNED_LENGTH = 461;
  /** RegularExpression Id. */
  int RETURNED_OCTET_LENGTH = 462;
  /** RegularExpression Id. */
  int RETURNED_SQLSTATE = 463;
  /** RegularExpression Id. */
  int RETURNING = 464;
  /** RegularExpression Id. */
  int RETURNS = 465;
  /** RegularExpression Id. */
  int REVOKE = 466;
  /** RegularExpression Id. */
  int RIGHT = 467;
  /** RegularExpression Id. */
  int RLIKE = 468;
  /** RegularExpression Id. */
  int ROLE = 469;
  /** RegularExpression Id. */
  int ROLLBACK = 470;
  /** RegularExpression Id. */
  int ROLLUP = 471;
  /** RegularExpression Id. */
  int ROUTINE = 472;
  /** RegularExpression Id. */
  int ROUTINE_CATALOG = 473;
  /** RegularExpression Id. */
  int ROUTINE_NAME = 474;
  /** RegularExpression Id. */
  int ROUTINE_SCHEMA = 475;
  /** RegularExpression Id. */
  int ROW = 476;
  /** RegularExpression Id. */
  int ROW_COUNT = 477;
  /** RegularExpression Id. */
  int ROW_NUMBER = 478;
  /** RegularExpression Id. */
  int ROWS = 479;
  /** RegularExpression Id. */
  int RUNNING = 480;
  /** RegularExpression Id. */
  int SAVEPOINT = 481;
  /** RegularExpression Id. */
  int SCALAR = 482;
  /** RegularExpression Id. */
  int SCALE = 483;
  /** RegularExpression Id. */
  int SCHEMA = 484;
  /** RegularExpression Id. */
  int SCHEMA_NAME = 485;
  /** RegularExpression Id. */
  int SCOPE = 486;
  /** RegularExpression Id. */
  int SCOPE_CATALOGS = 487;
  /** RegularExpression Id. */
  int SCOPE_NAME = 488;
  /** RegularExpression Id. */
  int SCOPE_SCHEMA = 489;
  /** RegularExpression Id. */
  int SCROLL = 490;
  /** RegularExpression Id. */
  int SEARCH = 491;
  /** RegularExpression Id. */
  int SECOND = 492;
  /** RegularExpression Id. */
  int SECONDS = 493;
  /** RegularExpression Id. */
  int SECTION = 494;
  /** RegularExpression Id. */
  int SECURITY = 495;
  /** RegularExpression Id. */
  int SEEK = 496;
  /** RegularExpression Id. */
  int SELECT = 497;
  /** RegularExpression Id. */
  int SELF = 498;
  /** RegularExpression Id. */
  int SENSITIVE = 499;
  /** RegularExpression Id. */
  int SEPARATOR = 500;
  /** RegularExpression Id. */
  int SEQUENCE = 501;
  /** RegularExpression Id. */
  int SERIALIZABLE = 502;
  /** RegularExpression Id. */
  int SERVER = 503;
  /** RegularExpression Id. */
  int SERVER_NAME = 504;
  /** RegularExpression Id. */
  int SESSION = 505;
  /** RegularExpression Id. */
  int SESSION_USER = 506;
  /** RegularExpression Id. */
  int SET = 507;
  /** RegularExpression Id. */
  int SETS = 508;
  /** RegularExpression Id. */
  int SET_MINUS = 509;
  /** RegularExpression Id. */
  int SHOW = 510;
  /** RegularExpression Id. */
  int SIMILAR = 511;
  /** RegularExpression Id. */
  int SIMPLE = 512;
  /** RegularExpression Id. */
  int SIZE = 513;
  /** RegularExpression Id. */
  int SKIP_ = 514;
  /** RegularExpression Id. */
  int SMALLINT = 515;
  /** RegularExpression Id. */
  int SOME = 516;
  /** RegularExpression Id. */
  int SOURCE = 517;
  /** RegularExpression Id. */
  int SPACE = 518;
  /** RegularExpression Id. */
  int SPECIFIC = 519;
  /** RegularExpression Id. */
  int SPECIFIC_NAME = 520;
  /** RegularExpression Id. */
  int SPECIFICTYPE = 521;
  /** RegularExpression Id. */
  int SQL = 522;
  /** RegularExpression Id. */
  int SQLEXCEPTION = 523;
  /** RegularExpression Id. */
  int SQLSTATE = 524;
  /** RegularExpression Id. */
  int SQLWARNING = 525;
  /** RegularExpression Id. */
  int SQL_BIGINT = 526;
  /** RegularExpression Id. */
  int SQL_BINARY = 527;
  /** RegularExpression Id. */
  int SQL_BIT = 528;
  /** RegularExpression Id. */
  int SQL_BLOB = 529;
  /** RegularExpression Id. */
  int SQL_BOOLEAN = 530;
  /** RegularExpression Id. */
  int SQL_CHAR = 531;
  /** RegularExpression Id. */
  int SQL_CLOB = 532;
  /** RegularExpression Id. */
  int SQL_DATE = 533;
  /** RegularExpression Id. */
  int SQL_DECIMAL = 534;
  /** RegularExpression Id. */
  int SQL_DOUBLE = 535;
  /** RegularExpression Id. */
  int SQL_FLOAT = 536;
  /** RegularExpression Id. */
  int SQL_INTEGER = 537;
  /** RegularExpression Id. */
  int SQL_INTERVAL_DAY = 538;
  /** RegularExpression Id. */
  int SQL_INTERVAL_DAY_TO_HOUR = 539;
  /** RegularExpression Id. */
  int SQL_INTERVAL_DAY_TO_MINUTE = 540;
  /** RegularExpression Id. */
  int SQL_INTERVAL_DAY_TO_SECOND = 541;
  /** RegularExpression Id. */
  int SQL_INTERVAL_HOUR = 542;
  /** RegularExpression Id. */
  int SQL_INTERVAL_HOUR_TO_MINUTE = 543;
  /** RegularExpression Id. */
  int SQL_INTERVAL_HOUR_TO_SECOND = 544;
  /** RegularExpression Id. */
  int SQL_INTERVAL_MINUTE = 545;
  /** RegularExpression Id. */
  int SQL_INTERVAL_MINUTE_TO_SECOND = 546;
  /** RegularExpression Id. */
  int SQL_INTERVAL_MONTH = 547;
  /** RegularExpression Id. */
  int SQL_INTERVAL_SECOND = 548;
  /** RegularExpression Id. */
  int SQL_INTERVAL_YEAR = 549;
  /** RegularExpression Id. */
  int SQL_INTERVAL_YEAR_TO_MONTH = 550;
  /** RegularExpression Id. */
  int SQL_LONGVARBINARY = 551;
  /** RegularExpression Id. */
  int SQL_LONGVARCHAR = 552;
  /** RegularExpression Id. */
  int SQL_LONGVARNCHAR = 553;
  /** RegularExpression Id. */
  int SQL_NCHAR = 554;
  /** RegularExpression Id. */
  int SQL_NCLOB = 555;
  /** RegularExpression Id. */
  int SQL_NUMERIC = 556;
  /** RegularExpression Id. */
  int SQL_NVARCHAR = 557;
  /** RegularExpression Id. */
  int SQL_REAL = 558;
  /** RegularExpression Id. */
  int SQL_SMALLINT = 559;
  /** RegularExpression Id. */
  int SQL_TIME = 560;
  /** RegularExpression Id. */
  int SQL_TIMESTAMP = 561;
  /** RegularExpression Id. */
  int SQL_TINYINT = 562;
  /** RegularExpression Id. */
  int SQL_TSI_DAY = 563;
  /** RegularExpression Id. */
  int SQL_TSI_FRAC_SECOND = 564;
  /** RegularExpression Id. */
  int SQL_TSI_HOUR = 565;
  /** RegularExpression Id. */
  int SQL_TSI_MICROSECOND = 566;
  /** RegularExpression Id. */
  int SQL_TSI_MINUTE = 567;
  /** RegularExpression Id. */
  int SQL_TSI_MONTH = 568;
  /** RegularExpression Id. */
  int SQL_TSI_QUARTER = 569;
  /** RegularExpression Id. */
  int SQL_TSI_SECOND = 570;
  /** RegularExpression Id. */
  int SQL_TSI_WEEK = 571;
  /** RegularExpression Id. */
  int SQL_TSI_YEAR = 572;
  /** RegularExpression Id. */
  int SQL_VARBINARY = 573;
  /** RegularExpression Id. */
  int SQL_VARCHAR = 574;
  /** RegularExpression Id. */
  int SQRT = 575;
  /** RegularExpression Id. */
  int START = 576;
  /** RegularExpression Id. */
  int STATE = 577;
  /** RegularExpression Id. */
  int STATEMENT = 578;
  /** RegularExpression Id. */
  int STATIC = 579;
  /** RegularExpression Id. */
  int STDDEV_POP = 580;
  /** RegularExpression Id. */
  int STDDEV_SAMP = 581;
  /** RegularExpression Id. */
  int STREAM = 582;
  /** RegularExpression Id. */
  int STRING_AGG = 583;
  /** RegularExpression Id. */
  int STRUCTURE = 584;
  /** RegularExpression Id. */
  int STYLE = 585;
  /** RegularExpression Id. */
  int SUBCLASS_ORIGIN = 586;
  /** RegularExpression Id. */
  int SUBMULTISET = 587;
  /** RegularExpression Id. */
  int SUBSET = 588;
  /** RegularExpression Id. */
  int SUBSTITUTE = 589;
  /** RegularExpression Id. */
  int SUBSTRING = 590;
  /** RegularExpression Id. */
  int SUBSTRING_REGEX = 591;
  /** RegularExpression Id. */
  int SUCCEEDS = 592;
  /** RegularExpression Id. */
  int SUM = 593;
  /** RegularExpression Id. */
  int SYMMETRIC = 594;
  /** RegularExpression Id. */
  int SYSTEM = 595;
  /** RegularExpression Id. */
  int SYSTEM_TIME = 596;
  /** RegularExpression Id. */
  int SYSTEM_USER = 597;
  /** RegularExpression Id. */
  int TABLE = 598;
  /** RegularExpression Id. */
  int TABLE_NAME = 599;
  /** RegularExpression Id. */
  int TABLESAMPLE = 600;
  /** RegularExpression Id. */
  int TEMPORARY = 601;
  /** RegularExpression Id. */
  int THEN = 602;
  /** RegularExpression Id. */
  int TIES = 603;
  /** RegularExpression Id. */
  int TIME = 604;
  /** RegularExpression Id. */
  int TIMESTAMP = 605;
  /** RegularExpression Id. */
  int TIMESTAMPADD = 606;
  /** RegularExpression Id. */
  int TIMESTAMPDIFF = 607;
  /** RegularExpression Id. */
  int TIMEZONE_HOUR = 608;
  /** RegularExpression Id. */
  int TIMEZONE_MINUTE = 609;
  /** RegularExpression Id. */
  int TINYINT = 610;
  /** RegularExpression Id. */
  int TO = 611;
  /** RegularExpression Id. */
  int TOP_LEVEL_COUNT = 612;
  /** RegularExpression Id. */
  int TRAILING = 613;
  /** RegularExpression Id. */
  int TRANSACTION = 614;
  /** RegularExpression Id. */
  int TRANSACTIONS_ACTIVE = 615;
  /** RegularExpression Id. */
  int TRANSACTIONS_COMMITTED = 616;
  /** RegularExpression Id. */
  int TRANSACTIONS_ROLLED_BACK = 617;
  /** RegularExpression Id. */
  int TRANSFORM = 618;
  /** RegularExpression Id. */
  int TRANSFORMS = 619;
  /** RegularExpression Id. */
  int TRANSLATE = 620;
  /** RegularExpression Id. */
  int TRANSLATE_REGEX = 621;
  /** RegularExpression Id. */
  int TRANSLATION = 622;
  /** RegularExpression Id. */
  int TREAT = 623;
  /** RegularExpression Id. */
  int TRIGGER = 624;
  /** RegularExpression Id. */
  int TRIGGER_CATALOG = 625;
  /** RegularExpression Id. */
  int TRIGGER_NAME = 626;
  /** RegularExpression Id. */
  int TRIGGER_SCHEMA = 627;
  /** RegularExpression Id. */
  int TRIM = 628;
  /** RegularExpression Id. */
  int TRIM_ARRAY = 629;
  /** RegularExpression Id. */
  int TRUE = 630;
  /** RegularExpression Id. */
  int TRUNCATE = 631;
  /** RegularExpression Id. */
  int TUMBLE = 632;
  /** RegularExpression Id. */
  int TYPE = 633;
  /** RegularExpression Id. */
  int UESCAPE = 634;
  /** RegularExpression Id. */
  int UNBOUNDED = 635;
  /** RegularExpression Id. */
  int UNCOMMITTED = 636;
  /** RegularExpression Id. */
  int UNCONDITIONAL = 637;
  /** RegularExpression Id. */
  int UNDER = 638;
  /** RegularExpression Id. */
  int UNION = 639;
  /** RegularExpression Id. */
  int UNIQUE = 640;
  /** RegularExpression Id. */
  int UNKNOWN = 641;
  /** RegularExpression Id. */
  int UNPIVOT = 642;
  /** RegularExpression Id. */
  int UNNAMED = 643;
  /** RegularExpression Id. */
  int UNNEST = 644;
  /** RegularExpression Id. */
  int UPDATE = 645;
  /** RegularExpression Id. */
  int UPPER = 646;
  /** RegularExpression Id. */
  int UPSERT = 647;
  /** RegularExpression Id. */
  int USAGE = 648;
  /** RegularExpression Id. */
  int USER = 649;
  /** RegularExpression Id. */
  int USER_DEFINED_TYPE_CATALOG = 650;
  /** RegularExpression Id. */
  int USER_DEFINED_TYPE_CODE = 651;
  /** RegularExpression Id. */
  int USER_DEFINED_TYPE_NAME = 652;
  /** RegularExpression Id. */
  int USER_DEFINED_TYPE_SCHEMA = 653;
  /** RegularExpression Id. */
  int USING = 654;
  /** RegularExpression Id. */
  int UTF8 = 655;
  /** RegularExpression Id. */
  int UTF16 = 656;
  /** RegularExpression Id. */
  int UTF32 = 657;
  /** RegularExpression Id. */
  int VALUE = 658;
  /** RegularExpression Id. */
  int VALUES = 659;
  /** RegularExpression Id. */
  int VALUE_OF = 660;
  /** RegularExpression Id. */
  int VAR_POP = 661;
  /** RegularExpression Id. */
  int VAR_SAMP = 662;
  /** RegularExpression Id. */
  int VARBINARY = 663;
  /** RegularExpression Id. */
  int VARCHAR = 664;
  /** RegularExpression Id. */
  int VARYING = 665;
  /** RegularExpression Id. */
  int VERSION = 666;
  /** RegularExpression Id. */
  int VERSIONING = 667;
  /** RegularExpression Id. */
  int VIEW = 668;
  /** RegularExpression Id. */
  int WEEK = 669;
  /** RegularExpression Id. */
  int WHEN = 670;
  /** RegularExpression Id. */
  int WHENEVER = 671;
  /** RegularExpression Id. */
  int WHERE = 672;
  /** RegularExpression Id. */
  int WIDTH_BUCKET = 673;
  /** RegularExpression Id. */
  int WINDOW = 674;
  /** RegularExpression Id. */
  int WITH = 675;
  /** RegularExpression Id. */
  int WITHIN = 676;
  /** RegularExpression Id. */
  int WITHOUT = 677;
  /** RegularExpression Id. */
  int WORK = 678;
  /** RegularExpression Id. */
  int WRAPPER = 679;
  /** RegularExpression Id. */
  int WRITE = 680;
  /** RegularExpression Id. */
  int XML = 681;
  /** RegularExpression Id. */
  int YEAR = 682;
  /** RegularExpression Id. */
  int YEARS = 683;
  /** RegularExpression Id. */
  int ZONE = 684;
  /** RegularExpression Id. */
  int IF = 685;
  /** RegularExpression Id. */
  int MATERIALIZED = 686;
  /** RegularExpression Id. */
  int UNSIGNED_INTEGER_LITERAL = 687;
  /** RegularExpression Id. */
  int APPROX_NUMERIC_LITERAL = 688;
  /** RegularExpression Id. */
  int DECIMAL_NUMERIC_LITERAL = 689;
  /** RegularExpression Id. */
  int EXPONENT = 690;
  /** RegularExpression Id. */
  int HEXDIGIT = 691;
  /** RegularExpression Id. */
  int WHITESPACE = 692;
  /** RegularExpression Id. */
  int BINARY_STRING_LITERAL = 693;
  /** RegularExpression Id. */
  int QUOTED_STRING = 694;
  /** RegularExpression Id. */
  int PREFIXED_STRING_LITERAL = 695;
  /** RegularExpression Id. */
  int UNICODE_STRING_LITERAL = 696;
  /** RegularExpression Id. */
  int CHARSETNAME = 697;
  /** RegularExpression Id. */
  int BIG_QUERY_DOUBLE_QUOTED_STRING = 698;
  /** RegularExpression Id. */
  int BIG_QUERY_QUOTED_STRING = 699;
  /** RegularExpression Id. */
  int UNICODE_QUOTED_ESCAPE_CHAR = 700;
  /** RegularExpression Id. */
  int LPAREN = 701;
  /** RegularExpression Id. */
  int RPAREN = 702;
  /** RegularExpression Id. */
  int LBRACE_D = 703;
  /** RegularExpression Id. */
  int LBRACE_T = 704;
  /** RegularExpression Id. */
  int LBRACE_TS = 705;
  /** RegularExpression Id. */
  int LBRACE_FN = 706;
  /** RegularExpression Id. */
  int LBRACE = 707;
  /** RegularExpression Id. */
  int RBRACE = 708;
  /** RegularExpression Id. */
  int LBRACKET = 709;
  /** RegularExpression Id. */
  int RBRACKET = 710;
  /** RegularExpression Id. */
  int SEMICOLON = 711;
  /** RegularExpression Id. */
  int DOT = 712;
  /** RegularExpression Id. */
  int COMMA = 713;
  /** RegularExpression Id. */
  int EQ = 714;
  /** RegularExpression Id. */
  int GT = 715;
  /** RegularExpression Id. */
  int LT = 716;
  /** RegularExpression Id. */
  int HOOK = 717;
  /** RegularExpression Id. */
  int COLON = 718;
  /** RegularExpression Id. */
  int LE = 719;
  /** RegularExpression Id. */
  int GE = 720;
  /** RegularExpression Id. */
  int NE = 721;
  /** RegularExpression Id. */
  int NE2 = 722;
  /** RegularExpression Id. */
  int PLUS = 723;
  /** RegularExpression Id. */
  int MINUS = 724;
  /** RegularExpression Id. */
  int STAR = 725;
  /** RegularExpression Id. */
  int SLASH = 726;
  /** RegularExpression Id. */
  int PERCENT_REMAINDER = 727;
  /** RegularExpression Id. */
  int CONCAT = 728;
  /** RegularExpression Id. */
  int NAMED_ARGUMENT_ASSIGNMENT = 729;
  /** RegularExpression Id. */
  int DOUBLE_PERIOD = 730;
  /** RegularExpression Id. */
  int QUOTE = 731;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE = 732;
  /** RegularExpression Id. */
  int VERTICAL_BAR = 733;
  /** RegularExpression Id. */
  int CARET = 734;
  /** RegularExpression Id. */
  int DOLLAR = 735;
  /** RegularExpression Id. */
  int HINT_BEG = 741;
  /** RegularExpression Id. */
  int COMMENT_END = 742;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 745;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 746;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 747;
  /** RegularExpression Id. */
  int BRACKET_QUOTED_IDENTIFIER = 749;
  /** RegularExpression Id. */
  int QUOTED_IDENTIFIER = 750;
  /** RegularExpression Id. */
  int BACK_QUOTED_IDENTIFIER = 751;
  /** RegularExpression Id. */
  int HYPHENATED_IDENTIFIER = 752;
  /** RegularExpression Id. */
  int IDENTIFIER = 753;
  /** RegularExpression Id. */
  int COLLATION_ID = 754;
  /** RegularExpression Id. */
  int UNICODE_QUOTED_IDENTIFIER = 755;
  /** RegularExpression Id. */
  int LETTER = 756;
  /** RegularExpression Id. */
  int DIGIT = 757;
  /** RegularExpression Id. */
  int BEL = 758;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int DQID = 1;
  /** Lexical state. */
  int BTID = 2;
  /** Lexical state. */
  int BQID = 3;
  /** Lexical state. */
  int BQHID = 4;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 5;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 6;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"A\"",
    "\"ABS\"",
    "\"ABSENT\"",
    "\"ABSOLUTE\"",
    "\"ACTION\"",
    "\"ADA\"",
    "\"ADD\"",
    "\"ADMIN\"",
    "\"AFTER\"",
    "\"ALL\"",
    "\"ALLOCATE\"",
    "\"ALLOW\"",
    "\"ALTER\"",
    "\"ALWAYS\"",
    "\"AND\"",
    "\"ANY\"",
    "\"APPLY\"",
    "\"ARE\"",
    "\"ARRAY\"",
    "\"ARRAY_AGG\"",
    "\"ARRAY_CONCAT_AGG\"",
    "\"ARRAY_MAX_CARDINALITY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"ASENSITIVE\"",
    "\"ASSERTION\"",
    "\"ASSIGNMENT\"",
    "\"ASYMMETRIC\"",
    "\"AT\"",
    "\"ATOMIC\"",
    "\"ATTRIBUTE\"",
    "\"ATTRIBUTES\"",
    "\"AUTHORIZATION\"",
    "\"AVG\"",
    "\"BEFORE\"",
    "\"BEGIN\"",
    "\"BEGIN_FRAME\"",
    "\"BEGIN_PARTITION\"",
    "\"BERNOULLI\"",
    "\"BETWEEN\"",
    "\"BIGINT\"",
    "\"BINARY\"",
    "\"BIT\"",
    "\"BLOB\"",
    "\"BOOLEAN\"",
    "\"BOTH\"",
    "\"BREADTH\"",
    "\"BY\"",
    "\"C\"",
    "\"CALL\"",
    "\"CALLED\"",
    "\"CARDINALITY\"",
    "\"CASCADE\"",
    "\"CASCADED\"",
    "\"CASE\"",
    "\"CAST\"",
    "\"CATALOG\"",
    "\"CATALOG_NAME\"",
    "\"CEIL\"",
    "\"CEILING\"",
    "\"CENTURY\"",
    "\"CHAIN\"",
    "\"CHAR\"",
    "\"CHAR_LENGTH\"",
    "\"CHARACTER\"",
    "\"CHARACTER_LENGTH\"",
    "\"CHARACTER_SET_CATALOG\"",
    "\"CHARACTER_SET_NAME\"",
    "\"CHARACTER_SET_SCHEMA\"",
    "\"CHARACTERISTICS\"",
    "\"CHARACTERS\"",
    "\"CHECK\"",
    "\"CLASSIFIER\"",
    "\"CLASS_ORIGIN\"",
    "\"CLOB\"",
    "\"CLOSE\"",
    "\"COALESCE\"",
    "\"COBOL\"",
    "\"COLLATE\"",
    "\"COLLATION\"",
    "\"COLLATION_CATALOG\"",
    "\"COLLATION_NAME\"",
    "\"COLLATION_SCHEMA\"",
    "\"COLLECT\"",
    "\"COLUMN\"",
    "\"COLUMN_NAME\"",
    "\"COMMAND_FUNCTION\"",
    "\"COMMAND_FUNCTION_CODE\"",
    "\"COMMIT\"",
    "\"COMMITTED\"",
    "\"CONDITION\"",
    "\"CONDITIONAL\"",
    "\"CONDITION_NUMBER\"",
    "\"CONNECT\"",
    "\"CONNECTION\"",
    "\"CONNECTION_NAME\"",
    "\"CONSTRAINT\"",
    "\"CONSTRAINT_CATALOG\"",
    "\"CONSTRAINT_NAME\"",
    "\"CONSTRAINT_SCHEMA\"",
    "\"CONSTRAINTS\"",
    "\"CONSTRUCTOR\"",
    "\"CONTAINS\"",
    "\"CONTINUE\"",
    "\"CONVERT\"",
    "\"CORR\"",
    "\"CORRESPONDING\"",
    "\"COUNT\"",
    "\"COVAR_POP\"",
    "\"COVAR_SAMP\"",
    "\"CREATE\"",
    "\"CROSS\"",
    "\"CUBE\"",
    "\"CUME_DIST\"",
    "\"CURRENT\"",
    "\"CURRENT_CATALOG\"",
    "\"CURRENT_DATE\"",
    "\"CURRENT_DEFAULT_TRANSFORM_GROUP\"",
    "\"CURRENT_PATH\"",
    "\"CURRENT_ROLE\"",
    "\"CURRENT_ROW\"",
    "\"CURRENT_SCHEMA\"",
    "\"CURRENT_TIME\"",
    "\"CURRENT_TIMESTAMP\"",
    "\"CURRENT_TRANSFORM_GROUP_FOR_TYPE\"",
    "\"CURRENT_USER\"",
    "\"CURSOR\"",
    "\"CURSOR_NAME\"",
    "\"CYCLE\"",
    "\"DATA\"",
    "\"DATABASE\"",
    "\"DATE\"",
    "\"DATETIME_INTERVAL_CODE\"",
    "\"DATETIME_INTERVAL_PRECISION\"",
    "\"DAY\"",
    "\"DAYS\"",
    "\"DEALLOCATE\"",
    "\"DEC\"",
    "\"DECADE\"",
    "\"DECIMAL\"",
    "\"DECLARE\"",
    "\"DEFAULT\"",
    "\"DEFAULTS\"",
    "\"DEFERRABLE\"",
    "\"DEFERRED\"",
    "\"DEFINE\"",
    "\"DEFINED\"",
    "\"DEFINER\"",
    "\"DEGREE\"",
    "\"DELETE\"",
    "\"DENSE_RANK\"",
    "\"DEPTH\"",
    "\"DEREF\"",
    "\"DERIVED\"",
    "\"DESC\"",
    "\"DESCRIBE\"",
    "\"DESCRIPTION\"",
    "\"DESCRIPTOR\"",
    "\"DETERMINISTIC\"",
    "\"DIAGNOSTICS\"",
    "\"DISALLOW\"",
    "\"DISCONNECT\"",
    "\"DISPATCH\"",
    "\"DISTINCT\"",
    "\"DOMAIN\"",
    "\"DOT\"",
    "\"DOUBLE\"",
    "\"DOW\"",
    "\"DOY\"",
    "\"DROP\"",
    "\"DYNAMIC\"",
    "\"DYNAMIC_FUNCTION\"",
    "\"DYNAMIC_FUNCTION_CODE\"",
    "\"EACH\"",
    "\"ELEMENT\"",
    "\"ELSE\"",
    "\"EMPTY\"",
    "\"ENCODING\"",
    "\"END\"",
    "\"END-EXEC\"",
    "\"END_FRAME\"",
    "\"END_PARTITION\"",
    "\"EPOCH\"",
    "\"EQUALS\"",
    "\"ERROR\"",
    "\"ESCAPE\"",
    "\"EVERY\"",
    "\"EXCEPT\"",
    "\"EXCEPTION\"",
    "\"EXCLUDE\"",
    "\"EXCLUDING\"",
    "\"EXEC\"",
    "\"EXECUTE\"",
    "\"EXISTS\"",
    "\"EXP\"",
    "\"EXPLAIN\"",
    "\"EXTEND\"",
    "\"EXTERNAL\"",
    "\"EXTRACT\"",
    "\"FALSE\"",
    "\"FETCH\"",
    "\"FILTER\"",
    "\"FINAL\"",
    "\"FIRST\"",
    "\"FIRST_VALUE\"",
    "\"FLOAT\"",
    "\"FLOOR\"",
    "\"FOLLOWING\"",
    "\"FOR\"",
    "\"FORMAT\"",
    "\"FOREIGN\"",
    "\"FORTRAN\"",
    "\"FOUND\"",
    "\"FRAC_SECOND\"",
    "\"FRAME_ROW\"",
    "\"FREE\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"FUNCTION\"",
    "\"FUSION\"",
    "\"G\"",
    "\"GENERAL\"",
    "\"GENERATED\"",
    "\"GEOMETRY\"",
    "\"GET\"",
    "\"GLOBAL\"",
    "\"GO\"",
    "\"GOTO\"",
    "\"GRANT\"",
    "\"GRANTED\"",
    "\"GROUP\"",
    "\"GROUP_CONCAT\"",
    "\"GROUPING\"",
    "\"GROUPS\"",
    "\"HAVING\"",
    "\"HIERARCHY\"",
    "\"HOLD\"",
    "\"HOP\"",
    "\"HOUR\"",
    "\"HOURS\"",
    "\"IDENTITY\"",
    "\"IGNORE\"",
    "\"ILIKE\"",
    "\"IMMEDIATE\"",
    "\"IMMEDIATELY\"",
    "\"IMPLEMENTATION\"",
    "\"IMPORT\"",
    "\"IN\"",
    "\"INCLUDE\"",
    "\"INCLUDING\"",
    "\"INCREMENT\"",
    "\"INDICATOR\"",
    "\"INITIAL\"",
    "\"INITIALLY\"",
    "\"INNER\"",
    "\"INOUT\"",
    "\"INPUT\"",
    "\"INSENSITIVE\"",
    "\"INSERT\"",
    "\"INSTANCE\"",
    "\"INSTANTIABLE\"",
    "\"INT\"",
    "\"INTEGER\"",
    "\"INTERSECT\"",
    "\"INTERSECTION\"",
    "\"INTERVAL\"",
    "\"INTO\"",
    "\"INVOKER\"",
    "\"IS\"",
    "\"ISODOW\"",
    "\"ISOYEAR\"",
    "\"ISOLATION\"",
    "\"JAVA\"",
    "\"JOIN\"",
    "\"JSON\"",
    "\"JSON_ARRAY\"",
    "\"JSON_ARRAYAGG\"",
    "\"JSON_EXISTS\"",
    "\"JSON_OBJECT\"",
    "\"JSON_OBJECTAGG\"",
    "\"JSON_QUERY\"",
    "\"JSON_VALUE\"",
    "\"K\"",
    "\"KEY\"",
    "\"KEY_MEMBER\"",
    "\"KEY_TYPE\"",
    "\"LABEL\"",
    "\"LAG\"",
    "\"LANGUAGE\"",
    "\"LARGE\"",
    "\"LAST\"",
    "\"LAST_VALUE\"",
    "\"LATERAL\"",
    "\"LEAD\"",
    "\"LEADING\"",
    "\"LEFT\"",
    "\"LENGTH\"",
    "\"LEVEL\"",
    "\"LIBRARY\"",
    "\"LIKE\"",
    "\"LIKE_REGEX\"",
    "\"LIMIT\"",
    "\"LN\"",
    "\"LOCAL\"",
    "\"LOCALTIME\"",
    "\"LOCALTIMESTAMP\"",
    "\"LOCATOR\"",
    "\"LOWER\"",
    "\"M\"",
    "\"MAP\"",
    "\"MATCH\"",
    "\"MATCHED\"",
    "\"MATCHES\"",
    "\"MATCH_NUMBER\"",
    "\"MATCH_RECOGNIZE\"",
    "\"MAX\"",
    "\"MAXVALUE\"",
    "\"MEASURES\"",
    "\"MEMBER\"",
    "\"MERGE\"",
    "\"MESSAGE_LENGTH\"",
    "\"MESSAGE_OCTET_LENGTH\"",
    "\"MESSAGE_TEXT\"",
    "\"METHOD\"",
    "\"MICROSECOND\"",
    "\"MILLISECOND\"",
    "\"MILLENNIUM\"",
    "\"MIN\"",
    "\"MINUTE\"",
    "\"MINUTES\"",
    "\"MINVALUE\"",
    "\"MOD\"",
    "\"MODIFIES\"",
    "\"MODULE\"",
    "\"MONTH\"",
    "\"MONTHS\"",
    "\"MORE\"",
    "\"MULTISET\"",
    "\"MUMPS\"",
    "\"NAME\"",
    "\"NAMES\"",
    "\"NANOSECOND\"",
    "\"NATIONAL\"",
    "\"NATURAL\"",
    "\"NCHAR\"",
    "\"NCLOB\"",
    "\"NESTING\"",
    "\"NEW\"",
    "\"NEXT\"",
    "\"NO\"",
    "\"NONE\"",
    "\"NORMALIZE\"",
    "\"NORMALIZED\"",
    "\"NOT\"",
    "\"NTH_VALUE\"",
    "\"NTILE\"",
    "\"NULL\"",
    "\"NULLABLE\"",
    "\"NULLIF\"",
    "\"NULLS\"",
    "\"NUMBER\"",
    "\"NUMERIC\"",
    "\"OBJECT\"",
    "\"OCCURRENCES_REGEX\"",
    "\"OCTET_LENGTH\"",
    "\"OCTETS\"",
    "\"OF\"",
    "\"OFFSET\"",
    "\"OLD\"",
    "\"OMIT\"",
    "\"ON\"",
    "\"ONE\"",
    "\"ONLY\"",
    "\"OPEN\"",
    "\"OPTION\"",
    "\"OPTIONS\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"ORDERING\"",
    "\"ORDINALITY\"",
    "\"OTHERS\"",
    "\"OUT\"",
    "\"OUTER\"",
    "\"OUTPUT\"",
    "\"OVER\"",
    "\"OVERLAPS\"",
    "\"OVERLAY\"",
    "\"OVERRIDING\"",
    "\"PAD\"",
    "\"PARAMETER\"",
    "\"PARAMETER_MODE\"",
    "\"PARAMETER_NAME\"",
    "\"PARAMETER_ORDINAL_POSITION\"",
    "\"PARAMETER_SPECIFIC_CATALOG\"",
    "\"PARAMETER_SPECIFIC_NAME\"",
    "\"PARAMETER_SPECIFIC_SCHEMA\"",
    "\"PARTIAL\"",
    "\"PARTITION\"",
    "\"PASCAL\"",
    "\"PASSING\"",
    "\"PASSTHROUGH\"",
    "\"PAST\"",
    "\"PATH\"",
    "\"PATTERN\"",
    "\"PER\"",
    "\"PERCENT\"",
    "\"PERCENTILE_CONT\"",
    "\"PERCENTILE_DISC\"",
    "\"PERCENT_RANK\"",
    "\"PERIOD\"",
    "\"PERMUTE\"",
    "\"PIVOT\"",
    "\"PLACING\"",
    "\"PLAN\"",
    "\"PLI\"",
    "\"PORTION\"",
    "\"POSITION\"",
    "\"POSITION_REGEX\"",
    "\"POWER\"",
    "\"PRECEDES\"",
    "\"PRECEDING\"",
    "\"PRECISION\"",
    "\"PREPARE\"",
    "\"PRESERVE\"",
    "\"PREV\"",
    "\"PRIMARY\"",
    "\"PRIOR\"",
    "\"PRIVILEGES\"",
    "\"PROCEDURE\"",
    "\"PUBLIC\"",
    "\"QUARTER\"",
    "\"RANGE\"",
    "\"RANK\"",
    "\"READ\"",
    "\"READS\"",
    "\"REAL\"",
    "\"RECURSIVE\"",
    "\"REF\"",
    "\"REFERENCES\"",
    "\"REFERENCING\"",
    "\"REGR_AVGX\"",
    "\"REGR_AVGY\"",
    "\"REGR_COUNT\"",
    "\"REGR_INTERCEPT\"",
    "\"REGR_R2\"",
    "\"REGR_SLOPE\"",
    "\"REGR_SXX\"",
    "\"REGR_SXY\"",
    "\"REGR_SYY\"",
    "\"RELATIVE\"",
    "\"RELEASE\"",
    "\"REPEATABLE\"",
    "\"REPLACE\"",
    "\"RESET\"",
    "\"RESPECT\"",
    "\"RESTART\"",
    "\"RESTRICT\"",
    "\"RESULT\"",
    "\"RETURN\"",
    "\"RETURNED_CARDINALITY\"",
    "\"RETURNED_LENGTH\"",
    "\"RETURNED_OCTET_LENGTH\"",
    "\"RETURNED_SQLSTATE\"",
    "\"RETURNING\"",
    "\"RETURNS\"",
    "\"REVOKE\"",
    "\"RIGHT\"",
    "\"RLIKE\"",
    "\"ROLE\"",
    "\"ROLLBACK\"",
    "\"ROLLUP\"",
    "\"ROUTINE\"",
    "\"ROUTINE_CATALOG\"",
    "\"ROUTINE_NAME\"",
    "\"ROUTINE_SCHEMA\"",
    "\"ROW\"",
    "\"ROW_COUNT\"",
    "\"ROW_NUMBER\"",
    "\"ROWS\"",
    "\"RUNNING\"",
    "\"SAVEPOINT\"",
    "\"SCALAR\"",
    "\"SCALE\"",
    "\"SCHEMA\"",
    "\"SCHEMA_NAME\"",
    "\"SCOPE\"",
    "\"SCOPE_CATALOGS\"",
    "\"SCOPE_NAME\"",
    "\"SCOPE_SCHEMA\"",
    "\"SCROLL\"",
    "\"SEARCH\"",
    "\"SECOND\"",
    "\"SECONDS\"",
    "\"SECTION\"",
    "\"SECURITY\"",
    "\"SEEK\"",
    "\"SELECT\"",
    "\"SELF\"",
    "\"SENSITIVE\"",
    "\"SEPARATOR\"",
    "\"SEQUENCE\"",
    "\"SERIALIZABLE\"",
    "\"SERVER\"",
    "\"SERVER_NAME\"",
    "\"SESSION\"",
    "\"SESSION_USER\"",
    "\"SET\"",
    "\"SETS\"",
    "\"MINUS\"",
    "\"SHOW\"",
    "\"SIMILAR\"",
    "\"SIMPLE\"",
    "\"SIZE\"",
    "\"SKIP\"",
    "\"SMALLINT\"",
    "\"SOME\"",
    "\"SOURCE\"",
    "\"SPACE\"",
    "\"SPECIFIC\"",
    "\"SPECIFIC_NAME\"",
    "\"SPECIFICTYPE\"",
    "\"SQL\"",
    "\"SQLEXCEPTION\"",
    "\"SQLSTATE\"",
    "\"SQLWARNING\"",
    "\"SQL_BIGINT\"",
    "\"SQL_BINARY\"",
    "\"SQL_BIT\"",
    "\"SQL_BLOB\"",
    "\"SQL_BOOLEAN\"",
    "\"SQL_CHAR\"",
    "\"SQL_CLOB\"",
    "\"SQL_DATE\"",
    "\"SQL_DECIMAL\"",
    "\"SQL_DOUBLE\"",
    "\"SQL_FLOAT\"",
    "\"SQL_INTEGER\"",
    "\"SQL_INTERVAL_DAY\"",
    "\"SQL_INTERVAL_DAY_TO_HOUR\"",
    "\"SQL_INTERVAL_DAY_TO_MINUTE\"",
    "\"SQL_INTERVAL_DAY_TO_SECOND\"",
    "\"SQL_INTERVAL_HOUR\"",
    "\"SQL_INTERVAL_HOUR_TO_MINUTE\"",
    "\"SQL_INTERVAL_HOUR_TO_SECOND\"",
    "\"SQL_INTERVAL_MINUTE\"",
    "\"SQL_INTERVAL_MINUTE_TO_SECOND\"",
    "\"SQL_INTERVAL_MONTH\"",
    "\"SQL_INTERVAL_SECOND\"",
    "\"SQL_INTERVAL_YEAR\"",
    "\"SQL_INTERVAL_YEAR_TO_MONTH\"",
    "\"SQL_LONGVARBINARY\"",
    "\"SQL_LONGVARCHAR\"",
    "\"SQL_LONGVARNCHAR\"",
    "\"SQL_NCHAR\"",
    "\"SQL_NCLOB\"",
    "\"SQL_NUMERIC\"",
    "\"SQL_NVARCHAR\"",
    "\"SQL_REAL\"",
    "\"SQL_SMALLINT\"",
    "\"SQL_TIME\"",
    "\"SQL_TIMESTAMP\"",
    "\"SQL_TINYINT\"",
    "\"SQL_TSI_DAY\"",
    "\"SQL_TSI_FRAC_SECOND\"",
    "\"SQL_TSI_HOUR\"",
    "\"SQL_TSI_MICROSECOND\"",
    "\"SQL_TSI_MINUTE\"",
    "\"SQL_TSI_MONTH\"",
    "\"SQL_TSI_QUARTER\"",
    "\"SQL_TSI_SECOND\"",
    "\"SQL_TSI_WEEK\"",
    "\"SQL_TSI_YEAR\"",
    "\"SQL_VARBINARY\"",
    "\"SQL_VARCHAR\"",
    "\"SQRT\"",
    "\"START\"",
    "\"STATE\"",
    "\"STATEMENT\"",
    "\"STATIC\"",
    "\"STDDEV_POP\"",
    "\"STDDEV_SAMP\"",
    "\"STREAM\"",
    "\"STRING_AGG\"",
    "\"STRUCTURE\"",
    "\"STYLE\"",
    "\"SUBCLASS_ORIGIN\"",
    "\"SUBMULTISET\"",
    "\"SUBSET\"",
    "\"SUBSTITUTE\"",
    "\"SUBSTRING\"",
    "\"SUBSTRING_REGEX\"",
    "\"SUCCEEDS\"",
    "\"SUM\"",
    "\"SYMMETRIC\"",
    "\"SYSTEM\"",
    "\"SYSTEM_TIME\"",
    "\"SYSTEM_USER\"",
    "\"TABLE\"",
    "\"TABLE_NAME\"",
    "\"TABLESAMPLE\"",
    "\"TEMPORARY\"",
    "\"THEN\"",
    "\"TIES\"",
    "\"TIME\"",
    "\"TIMESTAMP\"",
    "\"TIMESTAMPADD\"",
    "\"TIMESTAMPDIFF\"",
    "\"TIMEZONE_HOUR\"",
    "\"TIMEZONE_MINUTE\"",
    "\"TINYINT\"",
    "\"TO\"",
    "\"TOP_LEVEL_COUNT\"",
    "\"TRAILING\"",
    "\"TRANSACTION\"",
    "\"TRANSACTIONS_ACTIVE\"",
    "\"TRANSACTIONS_COMMITTED\"",
    "\"TRANSACTIONS_ROLLED_BACK\"",
    "\"TRANSFORM\"",
    "\"TRANSFORMS\"",
    "\"TRANSLATE\"",
    "\"TRANSLATE_REGEX\"",
    "\"TRANSLATION\"",
    "\"TREAT\"",
    "\"TRIGGER\"",
    "\"TRIGGER_CATALOG\"",
    "\"TRIGGER_NAME\"",
    "\"TRIGGER_SCHEMA\"",
    "\"TRIM\"",
    "\"TRIM_ARRAY\"",
    "\"TRUE\"",
    "\"TRUNCATE\"",
    "\"TUMBLE\"",
    "\"TYPE\"",
    "\"UESCAPE\"",
    "\"UNBOUNDED\"",
    "\"UNCOMMITTED\"",
    "\"UNCONDITIONAL\"",
    "\"UNDER\"",
    "\"UNION\"",
    "\"UNIQUE\"",
    "\"UNKNOWN\"",
    "\"UNPIVOT\"",
    "\"UNNAMED\"",
    "\"UNNEST\"",
    "\"UPDATE\"",
    "\"UPPER\"",
    "\"UPSERT\"",
    "\"USAGE\"",
    "\"USER\"",
    "\"USER_DEFINED_TYPE_CATALOG\"",
    "\"USER_DEFINED_TYPE_CODE\"",
    "\"USER_DEFINED_TYPE_NAME\"",
    "\"USER_DEFINED_TYPE_SCHEMA\"",
    "\"USING\"",
    "\"UTF8\"",
    "\"UTF16\"",
    "\"UTF32\"",
    "\"VALUE\"",
    "\"VALUES\"",
    "\"VALUE_OF\"",
    "\"VAR_POP\"",
    "\"VAR_SAMP\"",
    "\"VARBINARY\"",
    "\"VARCHAR\"",
    "\"VARYING\"",
    "\"VERSION\"",
    "\"VERSIONING\"",
    "\"VIEW\"",
    "\"WEEK\"",
    "\"WHEN\"",
    "\"WHENEVER\"",
    "\"WHERE\"",
    "\"WIDTH_BUCKET\"",
    "\"WINDOW\"",
    "\"WITH\"",
    "\"WITHIN\"",
    "\"WITHOUT\"",
    "\"WORK\"",
    "\"WRAPPER\"",
    "\"WRITE\"",
    "\"XML\"",
    "\"YEAR\"",
    "\"YEARS\"",
    "\"ZONE\"",
    "\"IF\"",
    "\"MATERIALIZED\"",
    "<UNSIGNED_INTEGER_LITERAL>",
    "<APPROX_NUMERIC_LITERAL>",
    "<DECIMAL_NUMERIC_LITERAL>",
    "<EXPONENT>",
    "<HEXDIGIT>",
    "<WHITESPACE>",
    "<BINARY_STRING_LITERAL>",
    "<QUOTED_STRING>",
    "<PREFIXED_STRING_LITERAL>",
    "<UNICODE_STRING_LITERAL>",
    "<CHARSETNAME>",
    "<BIG_QUERY_DOUBLE_QUOTED_STRING>",
    "<BIG_QUERY_QUOTED_STRING>",
    "<UNICODE_QUOTED_ESCAPE_CHAR>",
    "\"(\"",
    "\")\"",
    "<LBRACE_D>",
    "<LBRACE_T>",
    "<LBRACE_TS>",
    "<LBRACE_FN>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\".\"",
    "\",\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"?\"",
    "\":\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"||\"",
    "\"=>\"",
    "\"..\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"|\"",
    "\"^\"",
    "\"$\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*+\"",
    "\"*/\"",
    "<token of kind 743>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<token of kind 748>",
    "<BRACKET_QUOTED_IDENTIFIER>",
    "<QUOTED_IDENTIFIER>",
    "<BACK_QUOTED_IDENTIFIER>",
    "<HYPHENATED_IDENTIFIER>",
    "<IDENTIFIER>",
    "<COLLATION_ID>",
    "<UNICODE_QUOTED_IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<BEL>",
  };

}
